language: java
dist: xenial
jdk:
- openjdk8
notifications:
  email: true
env:
  global:
  - MVN_ARGS="--settings build/.travis.settings.xml -DskipTests=true"
branches:
  except:
  - gh-pages
cache:
  directories:
  - "$HOME/.m2"
before_install:
#- openssl aes-256-cbc -K $encrypted_a546dc4f1f8c_key -iv $encrypted_a546dc4f1f8c_iv -in surya.gpg.enc -out surya.gpg -d
#- gpg --import surya.gpg
- echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
- echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
- sudo apt-get update
- sudo apt-get install python
- nvm install 12
- npm install -g npm@6.x
install:
- curl -s https://codecov.io/bash > $HOME/codecov-bash.sh && chmod +x $HOME/codecov-bash.sh
before_script:
- echo "TRAVIS_TAG = '${TRAVIS_TAG}'"
- '[ -n "${TRAVIS_TAG}" ] && mvn versions:set -DnewVersion=${TRAVIS_TAG} -DgenerateBackupPoms=false
  || true'
script:
- mvn clean verify $MVN_ARGS
before_deploy:
- pip install --user bump2version
- npm install @semantic-release/changelog
- npm install @semantic-release/exec
- npm install @semantic-release/git
- npm install @semantic-release/github
deploy:
- provider: script
  script: npx semantic-release
  skip_cleanup: true
  on:
    branch: master
- provider: script
  script: mvn deploy $MVN_ARGS -DskipTests
  skip_cleanup: true
  on:
    tags: true
    jdk: openjdk8
- provider: script
  script: "./build/publish-javadoc.sh"
  skip_cleanup: true
  on:
    tags: true
    jdk: openjdk8
- provider: script
  script: "$HOME/codecov-bash.sh -s modules/coverage-reports/target/site/jacoco-aggregate
    -t $CODECOV_TOKEN"
  skip_cleanup: true
  on:
    condition: $TRAVIS_BRANCH == master || -n "$TRAVIS_TAG"
    jdk: openjdk8
